## Import Libries

In [1]:
import numpy as np
import pandas as pd

In [3]:
dataset = pd.read_csv("01. weather dataset.csv")
dataset.head()

Weather  Temp Play
0     Sunnt   Hot   No
1     Sunny   Hot   No
2  Overcast   Hot  Yes
3     Rainy  Mild  Yes
4     Rainy  Cool  Yes

In [26]:
x = dataset[['Weather']]
x

Weather
0      Sunnt
1      Sunny
2   Overcast
3      Rainy
4      Rainy
5      Rainy
6   Overcast
7      Sunny
8      Sunny
9      Rainy
10     Sunny
11  Overcast
12  Overcast
13     Rainy

In [29]:
y = dataset[['Temp']]
y

Temp
0    Hot
1    Hot
2    Hot
3   Mild
4   Cool
5   Cool
6   Cool
7   Mild
8   Cool
9   Mild
10  Mild
11  Mild
12   Hot
13  Mild

In [30]:
z = dataset[['Play']]
z

Play
0    No
1    No
2   Yes
3   Yes
4   Yes
5    No
6   Yes
7    No
8   Yes
9   Yes
10  Yes
11  Yes
12  Yes
13   No

In [31]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
weather_encoded = le.fit_transform(x)

c:\Users\Anas\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [32]:
weather_encoded

array([2, 3, 0, 1, 1, 1, 0, 3, 3, 1, 3, 0, 0, 1])

In [33]:
from sklearn.preprocessing import LabelEncoder
temp_encoded = LabelEncoder().fit_transform(y)

c:\Users\Anas\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [34]:
temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [35]:
from sklearn.preprocessing import LabelEncoder
play_encoded = LabelEncoder().fit_transform(z)

c:\Users\Anas\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [36]:
play_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [37]:
features = list(zip(weather_encoded, temp_encoded))
features

[(2, 1),
 (3, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (3, 2),
 (3, 0),
 (1, 2),
 (3, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [22]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)

In [38]:
model.fit(features,play_encoded)

KNeighborsClassifier(n_neighbors=3)

In [39]:
predicted = model.predict([[0,2]]) 
print(predicted) # 0:Overcast, 2:Mild

[1]
