In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn

In [26]:
df = pd.read_csv("01. Social Network Ads.csv")
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [27]:
df.shape

(400, 5)

In [28]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [29]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [30]:
x = df.iloc[:,[2,3]]
x.head()

Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [31]:
y = df.iloc[:,4]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [32]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.25,random_state=0)

In [33]:
print("Training data : ",xtrain.shape)
print("Training data : ",xtest.shape)

Training data :  (300, 2)
Training data :  (100, 2)


In [34]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.fit_transform(xtest)

In [35]:
from sklearn.svm import SVC
classifier = SVC(kernel="linear", random_state=0)
classifier.fit(xtrain,ytrain)

SVC(kernel='linear', random_state=0)

In [36]:
y_pred = classifier.predict(xtest)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [37]:
from sklearn import metrics
score = metrics.accuracy_score(ytest,y_pred)
score

0.88

In [38]:
from sklearn.svm import SVC
classifier = SVC(kernel="rbf")
classifier.fit(xtrain,ytrain)

SVC()

In [39]:
y_pred = classifier.predict(xtest)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)

In [40]:
from sklearn import metrics

print('Accuracy score with default rbf kernel')
score = metrics.accuracy_score(ytest,y_pred)
score

Accuracy score with default rbf kernel


0.93

In [41]:
from sklearn.svm import SVC
classifier = SVC(kernel="rbf", gamma=10, C=7, random_state=0)
classifier.fit(xtrain,ytrain)

SVC(C=7, gamma=10, random_state=0)

In [42]:
y_pred = classifier.predict(xtest)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=int64)

In [43]:
from sklearn import metrics
score = metrics.accuracy_score(ytest,y_pred)
score

0.91

In [44]:
svc=SVC(kernel='poly', degree=4)
svc.fit(xtrain,ytrain)

y_pred=svc.predict(xtest)
print("Accuracy score with poly kernel and degree ")
print(metrics.accuracy_score(ytest,y_pred))

Accuracy score with poly kernel and degree 
0.75
